"""Type stubs for shbt_sglt.native (v2.0 orchestration interface)."""

def run_sim_full(config_json: str) -> int: ...
def inject_faults(rate: float, target: str, duration: float) -> dict: ...
def observe_target(target_name: str, output: str) -> None: ...
def export_fits(input_bin: str, output_fits: str) -> None: ...
def verify_gate(gate_id: int) -> bool: ...
