/*
 * shbt_hal.h - GENERATED by scripts/export_os.py.  DO NOT EDIT.
 *   source   : kernel/include/shbt_hardware.h @ 7520a571d8e7
 *   generated: 2026-09-08T14:51:33Z
 *   formal   : recovery <= 105.90 ns PROVED (worst case 101.25 ns)
 *
 * Freestanding hardware abstraction layer: typed volatile accessors over the
 * SHBT-R MMIO aperture.  Depends only on <stdint.h> and shbt_hardware.h.
 */
#ifndef SHBT_HAL_H
#define SHBT_HAL_H

#include <stdint.h>
#include "shbt_hardware.h"

#ifdef __cplusplus
extern "C" {
#endif

#define SHBT_HAL_VERSION            "0.1.0"
#define SHBT_HAL_SOURCE_REVISION    "7520a571d8e7"
#define SHBT_HAL_FORMALLY_VERIFIED  1
#define SHBT_HAL_RECOVERY_WCET_NS_X100 10125U

static inline uint32_t shbt_hal_rd(uintptr_t off)
{
    return *(volatile uint32_t *)((uintptr_t)SHBT_MMIO + off);
}

static inline void shbt_hal_wr(uintptr_t off, uint32_t v)
{
    *(volatile uint32_t *)((uintptr_t)SHBT_MMIO + off) = v;
}

/* ---- scalar registers ------------------------------------------------ */
/* CTRL @ 0x0000 */
static inline uint32_t shbt_hal_read_ctrl(void) { return shbt_hal_rd(SHBT_REG_CTRL); }
static inline void     shbt_hal_write_ctrl(uint32_t v) { shbt_hal_wr(SHBT_REG_CTRL, v); }
static inline void     shbt_hal_set_ctrl(uint32_t m) { shbt_hal_wr(SHBT_REG_CTRL, shbt_hal_rd(SHBT_REG_CTRL) | m); }
static inline void     shbt_hal_clear_ctrl(uint32_t m) { shbt_hal_wr(SHBT_REG_CTRL, shbt_hal_rd(SHBT_REG_CTRL) & ~m); }

/* STATUS @ 0x0004 */
static inline uint32_t shbt_hal_read_status(void) { return shbt_hal_rd(SHBT_REG_STATUS); }
static inline void     shbt_hal_write_status(uint32_t v) { shbt_hal_wr(SHBT_REG_STATUS, v); }
static inline void     shbt_hal_set_status(uint32_t m) { shbt_hal_wr(SHBT_REG_STATUS, shbt_hal_rd(SHBT_REG_STATUS) | m); }
static inline void     shbt_hal_clear_status(uint32_t m) { shbt_hal_wr(SHBT_REG_STATUS, shbt_hal_rd(SHBT_REG_STATUS) & ~m); }

/* IRQ_STATUS @ 0x0008 */
static inline uint32_t shbt_hal_read_irq_status(void) { return shbt_hal_rd(SHBT_REG_IRQ_STATUS); }
static inline void     shbt_hal_write_irq_status(uint32_t v) { shbt_hal_wr(SHBT_REG_IRQ_STATUS, v); }
static inline void     shbt_hal_set_irq_status(uint32_t m) { shbt_hal_wr(SHBT_REG_IRQ_STATUS, shbt_hal_rd(SHBT_REG_IRQ_STATUS) | m); }
static inline void     shbt_hal_clear_irq_status(uint32_t m) { shbt_hal_wr(SHBT_REG_IRQ_STATUS, shbt_hal_rd(SHBT_REG_IRQ_STATUS) & ~m); }

/* IRQ_ENABLE @ 0x000C */
static inline uint32_t shbt_hal_read_irq_enable(void) { return shbt_hal_rd(SHBT_REG_IRQ_ENABLE); }
static inline void     shbt_hal_write_irq_enable(uint32_t v) { shbt_hal_wr(SHBT_REG_IRQ_ENABLE, v); }
static inline void     shbt_hal_set_irq_enable(uint32_t m) { shbt_hal_wr(SHBT_REG_IRQ_ENABLE, shbt_hal_rd(SHBT_REG_IRQ_ENABLE) | m); }
static inline void     shbt_hal_clear_irq_enable(uint32_t m) { shbt_hal_wr(SHBT_REG_IRQ_ENABLE, shbt_hal_rd(SHBT_REG_IRQ_ENABLE) & ~m); }

/* IRQ_CLEAR @ 0x0010 */
static inline uint32_t shbt_hal_read_irq_clear(void) { return shbt_hal_rd(SHBT_REG_IRQ_CLEAR); }
static inline void     shbt_hal_write_irq_clear(uint32_t v) { shbt_hal_wr(SHBT_REG_IRQ_CLEAR, v); }
static inline void     shbt_hal_set_irq_clear(uint32_t m) { shbt_hal_wr(SHBT_REG_IRQ_CLEAR, shbt_hal_rd(SHBT_REG_IRQ_CLEAR) | m); }
static inline void     shbt_hal_clear_irq_clear(uint32_t m) { shbt_hal_wr(SHBT_REG_IRQ_CLEAR, shbt_hal_rd(SHBT_REG_IRQ_CLEAR) & ~m); }

/* PUMP_ATTEN @ 0x0014 */
static inline uint32_t shbt_hal_read_pump_atten(void) { return shbt_hal_rd(SHBT_REG_PUMP_ATTEN); }
static inline void     shbt_hal_write_pump_atten(uint32_t v) { shbt_hal_wr(SHBT_REG_PUMP_ATTEN, v); }
static inline void     shbt_hal_set_pump_atten(uint32_t m) { shbt_hal_wr(SHBT_REG_PUMP_ATTEN, shbt_hal_rd(SHBT_REG_PUMP_ATTEN) | m); }
static inline void     shbt_hal_clear_pump_atten(uint32_t m) { shbt_hal_wr(SHBT_REG_PUMP_ATTEN, shbt_hal_rd(SHBT_REG_PUMP_ATTEN) & ~m); }

/* ECC_CTRL @ 0x0018 */
static inline uint32_t shbt_hal_read_ecc_ctrl(void) { return shbt_hal_rd(SHBT_REG_ECC_CTRL); }
static inline void     shbt_hal_write_ecc_ctrl(uint32_t v) { shbt_hal_wr(SHBT_REG_ECC_CTRL, v); }
static inline void     shbt_hal_set_ecc_ctrl(uint32_t m) { shbt_hal_wr(SHBT_REG_ECC_CTRL, shbt_hal_rd(SHBT_REG_ECC_CTRL) | m); }
static inline void     shbt_hal_clear_ecc_ctrl(uint32_t m) { shbt_hal_wr(SHBT_REG_ECC_CTRL, shbt_hal_rd(SHBT_REG_ECC_CTRL) & ~m); }

/* ECC_STATUS @ 0x001C */
static inline uint32_t shbt_hal_read_ecc_status(void) { return shbt_hal_rd(SHBT_REG_ECC_STATUS); }
static inline void     shbt_hal_write_ecc_status(uint32_t v) { shbt_hal_wr(SHBT_REG_ECC_STATUS, v); }
static inline void     shbt_hal_set_ecc_status(uint32_t m) { shbt_hal_wr(SHBT_REG_ECC_STATUS, shbt_hal_rd(SHBT_REG_ECC_STATUS) | m); }
static inline void     shbt_hal_clear_ecc_status(uint32_t m) { shbt_hal_wr(SHBT_REG_ECC_STATUS, shbt_hal_rd(SHBT_REG_ECC_STATUS) & ~m); }

/* ECC_SYNDROME @ 0x0020 */
static inline uint32_t shbt_hal_read_ecc_syndrome(void) { return shbt_hal_rd(SHBT_REG_ECC_SYNDROME); }
static inline void     shbt_hal_write_ecc_syndrome(uint32_t v) { shbt_hal_wr(SHBT_REG_ECC_SYNDROME, v); }
static inline void     shbt_hal_set_ecc_syndrome(uint32_t m) { shbt_hal_wr(SHBT_REG_ECC_SYNDROME, shbt_hal_rd(SHBT_REG_ECC_SYNDROME) | m); }
static inline void     shbt_hal_clear_ecc_syndrome(uint32_t m) { shbt_hal_wr(SHBT_REG_ECC_SYNDROME, shbt_hal_rd(SHBT_REG_ECC_SYNDROME) & ~m); }

/* ECC_ADDR @ 0x0024 */
static inline uint32_t shbt_hal_read_ecc_addr(void) { return shbt_hal_rd(SHBT_REG_ECC_ADDR); }
static inline void     shbt_hal_write_ecc_addr(uint32_t v) { shbt_hal_wr(SHBT_REG_ECC_ADDR, v); }
static inline void     shbt_hal_set_ecc_addr(uint32_t m) { shbt_hal_wr(SHBT_REG_ECC_ADDR, shbt_hal_rd(SHBT_REG_ECC_ADDR) | m); }
static inline void     shbt_hal_clear_ecc_addr(uint32_t m) { shbt_hal_wr(SHBT_REG_ECC_ADDR, shbt_hal_rd(SHBT_REG_ECC_ADDR) & ~m); }

/* ECC_DATA_LO @ 0x0028 */
static inline uint32_t shbt_hal_read_ecc_data_lo(void) { return shbt_hal_rd(SHBT_REG_ECC_DATA_LO); }
static inline void     shbt_hal_write_ecc_data_lo(uint32_t v) { shbt_hal_wr(SHBT_REG_ECC_DATA_LO, v); }
static inline void     shbt_hal_set_ecc_data_lo(uint32_t m) { shbt_hal_wr(SHBT_REG_ECC_DATA_LO, shbt_hal_rd(SHBT_REG_ECC_DATA_LO) | m); }
static inline void     shbt_hal_clear_ecc_data_lo(uint32_t m) { shbt_hal_wr(SHBT_REG_ECC_DATA_LO, shbt_hal_rd(SHBT_REG_ECC_DATA_LO) & ~m); }

/* ECC_DATA_HI @ 0x002C */
static inline uint32_t shbt_hal_read_ecc_data_hi(void) { return shbt_hal_rd(SHBT_REG_ECC_DATA_HI); }
static inline void     shbt_hal_write_ecc_data_hi(uint32_t v) { shbt_hal_wr(SHBT_REG_ECC_DATA_HI, v); }
static inline void     shbt_hal_set_ecc_data_hi(uint32_t m) { shbt_hal_wr(SHBT_REG_ECC_DATA_HI, shbt_hal_rd(SHBT_REG_ECC_DATA_HI) | m); }
static inline void     shbt_hal_clear_ecc_data_hi(uint32_t m) { shbt_hal_wr(SHBT_REG_ECC_DATA_HI, shbt_hal_rd(SHBT_REG_ECC_DATA_HI) & ~m); }

/* ECC_CHECK @ 0x0030 */
static inline uint32_t shbt_hal_read_ecc_check(void) { return shbt_hal_rd(SHBT_REG_ECC_CHECK); }
static inline void     shbt_hal_write_ecc_check(uint32_t v) { shbt_hal_wr(SHBT_REG_ECC_CHECK, v); }
static inline void     shbt_hal_set_ecc_check(uint32_t m) { shbt_hal_wr(SHBT_REG_ECC_CHECK, shbt_hal_rd(SHBT_REG_ECC_CHECK) | m); }
static inline void     shbt_hal_clear_ecc_check(uint32_t m) { shbt_hal_wr(SHBT_REG_ECC_CHECK, shbt_hal_rd(SHBT_REG_ECC_CHECK) & ~m); }

/* TIMER_LO @ 0x0034 */
static inline uint32_t shbt_hal_read_timer_lo(void) { return shbt_hal_rd(SHBT_REG_TIMER_LO); }
static inline void     shbt_hal_write_timer_lo(uint32_t v) { shbt_hal_wr(SHBT_REG_TIMER_LO, v); }
static inline void     shbt_hal_set_timer_lo(uint32_t m) { shbt_hal_wr(SHBT_REG_TIMER_LO, shbt_hal_rd(SHBT_REG_TIMER_LO) | m); }
static inline void     shbt_hal_clear_timer_lo(uint32_t m) { shbt_hal_wr(SHBT_REG_TIMER_LO, shbt_hal_rd(SHBT_REG_TIMER_LO) & ~m); }

/* TIMER_HI @ 0x0038 */
static inline uint32_t shbt_hal_read_timer_hi(void) { return shbt_hal_rd(SHBT_REG_TIMER_HI); }
static inline void     shbt_hal_write_timer_hi(uint32_t v) { shbt_hal_wr(SHBT_REG_TIMER_HI, v); }
static inline void     shbt_hal_set_timer_hi(uint32_t m) { shbt_hal_wr(SHBT_REG_TIMER_HI, shbt_hal_rd(SHBT_REG_TIMER_HI) | m); }
static inline void     shbt_hal_clear_timer_hi(uint32_t m) { shbt_hal_wr(SHBT_REG_TIMER_HI, shbt_hal_rd(SHBT_REG_TIMER_HI) & ~m); }

/* TEMP_MK @ 0x003C */
static inline uint32_t shbt_hal_read_temp_mk(void) { return shbt_hal_rd(SHBT_REG_TEMP_MK); }
static inline void     shbt_hal_write_temp_mk(uint32_t v) { shbt_hal_wr(SHBT_REG_TEMP_MK, v); }
static inline void     shbt_hal_set_temp_mk(uint32_t m) { shbt_hal_wr(SHBT_REG_TEMP_MK, shbt_hal_rd(SHBT_REG_TEMP_MK) | m); }
static inline void     shbt_hal_clear_temp_mk(uint32_t m) { shbt_hal_wr(SHBT_REG_TEMP_MK, shbt_hal_rd(SHBT_REG_TEMP_MK) & ~m); }

/* ---- phase register array ------------------------------------------- */
#define SHBT_HAL_PHASE_OFFSET(ch)  (0x1000U + 4U * (uintptr_t)(ch))
static inline uint32_t shbt_hal_read_phase(uint32_t ch) { return shbt_hal_rd(SHBT_HAL_PHASE_OFFSET(ch)); }
static inline void     shbt_hal_write_phase(uint32_t ch, uint32_t v) { shbt_hal_wr(SHBT_HAL_PHASE_OFFSET(ch), v); }

/* ---- 64-bit free-running timer (hi/lo/hi read with retry) ------------ */
static inline uint64_t shbt_hal_read_timer_ns(void)
{
    uint32_t hi1, lo, hi2;
    do {
        hi1 = shbt_hal_read_timer_hi();
        lo  = shbt_hal_read_timer_lo();
        hi2 = shbt_hal_read_timer_hi();
    } while (hi1 != hi2);
    return ((uint64_t)hi1 << 32) | lo;
}

#ifdef __cplusplus
}
#endif
#endif /* SHBT_HAL_H */
